### ISSUE TITLE
Alert: The Group Policy Update health monitor has failed

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Nathangau/SecurityMonitoring#1]
Hello.

We sometimes get alerts from different servers that Group Policy has a problem. However, in the body of the alert, we see that the policy is applied successfully.

```
Alert: The Group Policy Update health monitor has failed.
Source: DC01
Path: DC01.holding.com
Description: Group Policy failed to refresh properly.  Gpupdate output: 

Updating policy...



Computer Policy update has completed successfully.

User Policy update has completed successfully.
```

Windows Server 2016 / SCOM 2016

**Comment by Nathangau** [comment]
Are you sure that this is the Security Monitoring MP? There is no Group Policy Update health monitor. I do have a rule tracking and alerting on GPO changes, but nothing regarding the health of Group Policy.

**Comment by Aleksey-Maksimov** [comment]
I'm sorry. The problem is really in another package "Active Directory Domain Controller Server 2016 and above Computer Role MP".
